service: projectManagement
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  httpApi:
    cors: true
    
functions:

  memberDetailfunction:
    handler: member.handler1
    events:
      - httpApi:
          method: ANY
          path: /members/{param}
          
  memberfunction:
    handler: member.handler2
    events:
      - httpApi:
          path: /members
          method: ANY

  taskDetailfunction:
    handler: task.handler1
    events:
      - httpApi:
          path: /tasks/{param}
          method: ANY
          
  taskfunction:
    handler: task.handler2
    events:
      - httpApi:
          path: /tasks
          method: ANY

          
